# Recomendation of musics from GPT: tokens - GPT - probabilities

import argparse
import os
from pathlib import Path

import numpy as np
import pandas as pd
from contextlib import nullcontext  # autocast for GPU
import pickle
import torch
from urllib.parse import urlparse

import spotipy
from dotenv import load_dotenv
from spotipy.oauth2 import SpotifyOAuth

from model import GPT, GPTConfig

parser = argparse.ArgumentParser()

parser.add_argument("--checkpoint", type=str, default="./out/checkpoint_play.pt")
parser.add_argument("--mode", type=str, choices=["validation", "spotify"], default="validation",
    help=(
        "validation: selects a playlist from the offline corpus "
        "spotify: loads a playlist from the authenticated Spotify account (mine)"
    )
)
parser.add_argument("--playlist", type=str, default=None, help="Spotify playlist URL")
parser.add_argument("--context-size", type=int, default=50, help="Number of playlist tracks used as GPT context")
parser.add_argument("--num-recommendations", type=int, default=3, help="Number of tracks generated by the GPT")
parser.add_argument("--temperature", type=float, default=0.8, help="Aleatority choice measure")
parser.add_argument("--top-k", type=int, default=50, help="Sampling top-k most likely tracks for recommendation")

args = parser.parse_args()

if args.mode == "spotify" and not args.playlist:
    parser.error("--playlist is required when --mode spotify.")

def create_spotify_client():
    """
    Authenticate the current user with Spotify OAuth
    and return an authenticated Spotify client
    """

    load_dotenv()

    client_id = os.getenv("SPOTIPY_CLIENT_ID")
    client_secret = os.getenv("SPOTIPY_CLIENT_SECRET")
    redirect_uri = os.getenv("SPOTIPY_REDIRECT_URI")

    missing_variables = [
        variable_name
        for variable_name, variable_value in {
            "SPOTIPY_CLIENT_ID": client_id,
            "SPOTIPY_CLIENT_SECRET": client_secret,
            "SPOTIPY_REDIRECT_URI": redirect_uri,
        }.items()
        if not variable_value
    ]

    if missing_variables:
        raise EnvironmentError(
            "Missing Spotify environment variables: "
            f"{', '.join(missing_variables)}"
        )

    auth_manager = SpotifyOAuth(  # Authenticator
        client_id=client_id,
        client_secret=client_secret,
        redirect_uri=redirect_uri,
        scope="playlist-read-private",
        cache_path=".cache-spotify",  # where track tokens will save
        open_browser=True,
    )

    return spotipy.Spotify(
        auth_manager=auth_manager,
        requests_timeout=20,
        retries=3,
    )

def load_playlist_track_uris(spotify_client, playlist_id):
    """
    Load all valid track URIs from a Spotify playlist.

    Handles pagination and ignores:
    - unavailable tracks
    - local files
    - podcast episodes
    - malformed items
    """

    track_uris = []
    # API: returns items from playlist: tracks
    response = spotify_client.playlist_items(   
        playlist_id,
        limit=50,   # pages limit
        offset=0,    # first item
        additional_types=("track",), # only type track
    )
    # process pages
    while response:  
        # print("Response keys:", response.keys())
        #print("First playlist item:", response["items"][0])
        for playlist_item in response["items"]:
            track = playlist_item.get("item")  # item = track{"name":..., "uri":..., "type":...}

            if not track:   # ignore items without track
                continue

            if track.get("type") != "track":  # only tracks
                continue

            if playlist_item.get("is_local"):  # ignore local files
                continue

            track_uri = track.get("uri")

            if track_uri:
                track_uris.append(track_uri)  # page items

        if response.get("next"):
            response = spotify_client.next(response) # advance other tracks

        else:
            break

    if not track_uris:
        raise ValueError(
            "No valid Spotify tracks in the playlist."
        )

    return track_uris

def convert_playlist_uris_to_tokens(playlist_track_uris, uri_to_token):
    """
    URIs not present in the vocabulary are ignored.
    """

    playlist_tokens = []
    unknown_uris = []

    for track_uri in playlist_track_uris:

        if track_uri in uri_to_token:
            track_token = uri_to_token[track_uri]
            playlist_tokens.append(track_token)
        else:
            unknown_uris.append(track_uri)

    if not playlist_tokens:
        raise ValueError(
            "None of the playlist tracks exist in the model vocabulary."
        )

    return playlist_tokens, unknown_uris

corpus_path = "./corpus/corpus.bin"
vocab_path = "./corpus/vocab.pkl"
stats_path = "./corpus/stats.csv"

context_size = args.context_size
num_recommendations = args.num_recommendations
temperature = args.temperature
top_k = args.top_k

seed = 42 # control playlist choice

if seed is not None:
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

device = "cuda" if torch.cuda.is_available() else "cpu"

if device == "cuda":
    print(f"GPU: {torch.cuda.get_device_name(0)}")

checkpoint_path = Path(args.checkpoint)

if not checkpoint_path.is_file():
    raise FileNotFoundError(
        f"Checkpoint não encontrado: {checkpoint_path}")

# load 
checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)

corpus_path = Path(corpus_path)
vocab_path = Path(vocab_path)

print("Checkpoint carregado com sucesso.")

# Recriate architeture model

# model arguments
model_args = checkpoint["model_args"]

for name, value in model_args.items():
    print(f"{name}: {value}")

gpt_config = GPTConfig(**model_args)

model = GPT(gpt_config)

# load weigths
state_dict = checkpoint["model"]

model.load_state_dict(state_dict)

# insert all parameters in cuda
_ = model.to(device)
# inference
model.eval()

# validation
model_device = next(model.parameters()).device

number_of_parameters = sum(parameter.numel() for parameter in model.parameters())

print(f"Device: {model_device}")
print(f"Parameters: {number_of_parameters:,}")

print("Best val loss:", checkpoint.get("best_val_loss", "desconhecida"))

# Mixed precision during inference
if device == "cuda":
    if torch.cuda.is_bf16_supported():
        inference_dtype = torch.bfloat16
    else:
        inference_dtype = torch.float16
    ctx = torch.amp.autocast(device_type="cuda", dtype=inference_dtype)
else:
    ctx = nullcontext()

with open(vocab_path, "rb") as file:
    vocabs = pickle.load(file)

if "track_uri" not in vocabs:
    raise KeyError(
        "O vocab.pkl não contém a chave 'track_uri'. "
        f"Chaves encontradas: {list(vocabs.keys())}"
    )

track_vocab = vocabs["track_uri"]

required_vocab_keys = {"uri_to_token", "token_to_uri"}

missing_vocab_keys = (required_vocab_keys - set(track_vocab))

if missing_vocab_keys:
    raise KeyError(
        "The track vocabulary is missing required mappings: "
        f"{sorted(missing_vocab_keys)}"
    )

token_to_uri = track_vocab["token_to_uri"]
uri_to_token = track_vocab["uri_to_token"]

# avoid no track tokens
valid_track_tokens = set(token_to_uri)

print(f"Musics in vocab: {len(valid_track_tokens):,}")
print(f"First token: {min(valid_track_tokens)}")
print(f"Last token: {max(valid_track_tokens)}")

def extract_playlist_id(playlist_reference): # for mode spotify
    """
    Extract a Spotify playlist ID from:
    - Spotify URL
    - Spotify URI
    - raw playlist ID
    """

    if not isinstance(playlist_reference, str):
        raise TypeError(
            "Playlist reference must be a string"
        )

    playlist_reference = playlist_reference.strip() # clean string

    if not playlist_reference:
        raise ValueError(
            "Playlist reference cannot be empty"
        )

    # Spotify URI:
    # spotify:playlist:37i9dQZF1DX...
    if playlist_reference.startswith("spotify:playlist:"):
        playlist_id = playlist_reference.split(":")[-1]

    # Spotify URL:
    # https://open.spotify.com/playlist/37i9dQZF1DX.....
    elif "open.spotify.com" in playlist_reference:
        parsed_url = urlparse(playlist_reference)

        path_parts = [part for part in parsed_url.path.split("/") if part]

        if (len(path_parts) < 2 or path_parts[0] != "playlist"):
            raise ValueError("Invalid Spotify playlist URL")

        playlist_id = path_parts[1] # /37i9dQZF1DX.....

    # Raw playlist ID
    else:
        playlist_id = playlist_reference

    if not playlist_id:
        raise ValueError("Could not extract the Spotify playlist ID")

    return playlist_id


if args.mode == "validation":

    corpus = np.memmap(corpus_path, dtype=np.uint32, mode="r")

    corpus_size = len(corpus)
    train_end = corpus_size * 80 // 100 # 80%

    print(f"Tokens no corpus: {corpus_size:,}")

    # Playlist identifier

    stats_path = Path(stats_path)

    stats = pd.read_csv(stats_path)

    print("\n--- Playlist statistics ---")
    print(f"Number of playlists: {len(stats):,}")
    print("\nFirst playlists:")
    print(stats.head())

    # Select elegible playlists
    minimum_playlist_size = (context_size + num_recommendations)

    eligible_playlists = stats[stats["num_tracks"] >= minimum_playlist_size].copy()

    print("Eligible playlists:", f"{len(eligible_playlists):,}")

    eligible_playlists = eligible_playlists[eligible_playlists["inicio"] >= train_end]

    # Random playlist

    # select 1 random playlist
    selected_playlist = eligible_playlists.sample(n=1, random_state=seed).iloc[0]

    playlist_id = int(selected_playlist["pid"])
    playlist_start = int(selected_playlist["inicio"])
    playlist_end = int(selected_playlist["fim"])
    playlist_size = int(selected_playlist["num_tracks"])


    # tokens from playlist 
    playlist_tokens = corpus[playlist_start:playlist_end].astype(np.int64)

    print("\nPlaylist tokens:")
    print(playlist_tokens)

    # first tracks are used as input for the GPT
    context_tokens = playlist_tokens[:context_size]

    # following tracks are used only for comparison/validation
    real_continuation = playlist_tokens[context_size:context_size + num_recommendations]

    print("\n--- Validation mode ---")
    print(f"Playlist ID: {playlist_id}")
    print(f"Number of tracks: {playlist_size}")
    
    print("\nContext tokens:")
    print(context_tokens)

    print("\nReal continuation:")
    print(real_continuation)

    prompt = torch.tensor(context_tokens, dtype=torch.long, device=device).unsqueeze(0)

elif args.mode == "spotify":

    playlist_id = extract_playlist_id(args.playlist)

    print("\n--- Spotify mode ---")
    print(f"Playlist reference: {args.playlist}")
    print(f"Playlist ID: {playlist_id}")

    spotify_client = create_spotify_client()

    current_user = spotify_client.current_user()

    print("\nSpotify authentication successful.")
    print(f"Authenticated user: {current_user.get('display_name')}")
    print(f"User ID: {current_user.get('id')}")

    playlist_track_uris = load_playlist_track_uris(
        spotify_client=spotify_client,
        playlist_id=playlist_id
    )

    playlist_data = spotify_client.playlist(playlist_id, fields="name")

    playlist_name = playlist_data["name"]

    playlist_tokens, unknown_uris = convert_playlist_uris_to_tokens(
        playlist_track_uris=playlist_track_uris,
        uri_to_token=uri_to_token
    )

    print("\n--- Vocabulary coverage ---")
    print(f"Playlist name: {playlist_name}")
    print(f"Playlist tracks: {len(playlist_track_uris)}")
    print(f"Valid tracks found: {len(playlist_track_uris)}")
    print(f"Known tracks: {len(playlist_tokens)}")
    print(f"Unknown tracks: {len(unknown_uris)}")

    context_tokens = playlist_tokens[-context_size:]

    prompt = torch.tensor(context_tokens, dtype=torch.long, device=device).unsqueeze(0)


@torch.inference_mode()
def generate_recommendations(model, prompt, num_recommendations, valid_track_tokens, temperature, top_k,):
    generated = prompt.clone()

    recommendations = [] # new recommendation tokens
    # block repeated songs: {songA, songB, ...} no recommended this songs anymore
    blocked_tokens = set(int(token) for token in prompt[0].tolist() if token in valid_track_tokens)

    for _ in range(num_recommendations):

        # if the sequence context is growing too long we must crop it at block_size
        idx_cond = generated[:, -model.config.block_size:] # [token[1], ..., token[block_size]]

        # forward the model to get the logits for the index in the sequence 
        with ctx:
            logits, _ = model(idx_cond) # tokens -> logits(scores)

        next_token_logits = logits[:, -1, :] / temperature # new token score after the last context token. [batch, position, tokens_vocab]

        # only tokens in the vocab
        allowed_mask = torch.zeros(model.config.vocab_size, dtype=torch.bool, device=device,) # (0,block_size)

        allowed_tokens = [token for token in valid_track_tokens
            if (token < model.config.vocab_size and token not in blocked_tokens)]

        if not allowed_tokens:
            break

        allowed_mask[allowed_tokens] = True

        next_token_logits[:,~allowed_mask] = float("-inf")

        effective_top_k = min(top_k, len(allowed_tokens))  # most top_k likely songs

        top_values, _ = torch.topk(next_token_logits, effective_top_k,) # if top_k > allowed tokens

        cutoff = top_values[:, [-1]] # minor value

        next_token_logits[next_token_logits < cutoff] = float("-inf") # all not permited tokens with -infty, with 0 when softmax

        probabilities = torch.softmax(next_token_logits, dim=-1,) # probalility distribution: sum(logits) =~ 1

        next_token = torch.multinomial(probabilities, num_samples=1,) # next song token. Multinomial: weighted random selection of songs

        token_value = int(next_token.item())

        recommendations.append(token_value)
        blocked_tokens.add(token_value) # dont recommend same songs

        generated = torch.cat((generated, next_token), dim=1,) # [songA, songB, songC(forecast)]

    return recommendations # (0, num_recommendations)

def get_track_descriptions(spotify_client, track_tokens, token_to_uri):

    track_descriptions = []

    for token in track_tokens:
        track_uri = token_to_uri.get(int(token))

        if not track_uri:
            continue

        try:
            track = spotify_client.track(track_uri)

        except spotipy.SpotifyException as error:
            print(f"Could not load track metadata for token {token}: {error}")
            continue

        if not track:
            continue

        track_name = track["name"]

        artist_names = [artist["name"] for artist in track["artists"]] # list
        album_name = track["album"]["name"] # dict

        artists = ", ".join(artist_names)

        track_descriptions.append(
            {
                "name": track_name,
                "artists": artists,
                "album":album_name
            }
        )

    return track_descriptions

recommended_tokens = generate_recommendations(
    model=model,
    prompt=prompt,
    num_recommendations=num_recommendations,
    valid_track_tokens=valid_track_tokens,
    temperature=temperature,
    top_k=top_k,
)

if args.mode == "validation":

    real_token_set = {int(token) for token in real_continuation}

    recommended_token_set = set(recommended_tokens)

    matches = real_token_set & recommended_token_set

    precision_at_k = (len(matches) / len(recommended_tokens) if recommended_tokens else 0.0)

    recall_at_k = (len(matches) / len(real_continuation) if len(real_continuation) > 0 else 0.0)

    hit_rate_at_k = float(len(matches) > 0)

    print("\nSUMMARY")
    print(f"Playlist ID: {playlist_id}")
    print(f"Playlist size: {playlist_size}")
    print(f"Context tracks: {len(context_tokens)}")
    print(f"Real continuation tracks: {len(real_continuation)}")
    print(f"Recommended tracks: {len(recommended_tokens)}")
    print(f"Exact matches: {len(matches)}")
    print(f"Precision@{num_recommendations}: " f"{precision_at_k:.2%}"
    )
    print(f"Recall@{num_recommendations}: " f"{recall_at_k:.2%}")
    print(f"Hit Rate@{num_recommendations}: "f"{hit_rate_at_k:.2%}")

elif args.mode == "spotify":

    recommended_tracks = get_track_descriptions(
        spotify_client=spotify_client,
        track_tokens=recommended_tokens,
        token_to_uri=token_to_uri,
    )

    print("\nGPT RECOMMENDATIONS")

    print("\nRecommended tokens:")
    print(recommended_tokens)

    for position, track in enumerate(recommended_tracks, start=1):
        print(f"\n{position:02d}. {track['name']} — {track['artists']}\n"
            f"Album: {track['album']}")
